name: 01 - Building BLocks
on: [workflow_dispatch]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world!"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "I am"
          echo "a multi-line"
          echo "script"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye, world!"
