name: 02 - workflow event
on: [push, pull_request, workflow_dispatch]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show a trigger
        run: echo "Event name is ${{ github.event_name }}"
