name: 02 - workflow event
on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show a trigger
        run: echo "Event name is ${{ github.event_name }}"
