name: 04 0 - Using Actions
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app # more clear than using cd 04-using....
# 1. Install dependencies
# 2. Execute automated tests