name: 04 - Using Actions
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/my-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test
# 1. Install dependencies
# 2. Execute automated tests