name: 05 - 1 - Filters - Activity Types
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Run on push
        run: echo "Running whenever a PR is opened or synced"